### ISSUE TITLE
Разбить тему проекта на эпики

### ISSUE THREAD

**Issue by ArtiomNosov** [ArtiomNosov/it-classes-2024-dictionary-of-evolutions#2]

**Comment by ArtiomNosov** [comment]
организационное

**Comment by Vlados-SOS5** [comment]
1. Заполнить БД
2. Провести тестирование
3. Сделать аккаунтирование(бэкэнд) 
4. Сделать анимации и слайдер на сайте(фронтэнд) + экспорт(бэкэнд)
5. Вставить нейросеть с картинками
